services:
  web: #или nginx
    image: nginx
    ports:
      - 82:80    #ТОЧНО 80? когда запускаю http://localhost:81/index.php выдает ошибку
    volumes:
      - '/home/mdr11/projects/online_shop/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
      - '/home/mdr11/projects/online_shop:/var/www/html'


  php-fpm:
    build: ./docker/php
    volumes:
      - '/home/mdr11/projects/online_shop:/var/www/html'


  postgres:
    image: postgres:16
    environment:
      - POSTGRES_USER={$DB_USER}
      - POSTGRES_PASSWORD={$DB_PASSWORD}
      - POSTGRES_DB={$DB}
    #ports:
     # -54322:5432